//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugCapture.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationTicket
    {
        public int ApplicationTicketId { get; set; }
        public int TicketId { get; set; }
        public int ApplicationId { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
