//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugCapture.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.ApplicationTickets = new HashSet<ApplicationTicket>();
        }
    
        public int ApplicationId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
    
        public virtual ICollection<ApplicationTicket> ApplicationTickets { get; set; }
    }
}
