//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugCapture.Domain.DataConnections
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ICT_Bug_CaptureEntities : DbContext
    {
        public ICT_Bug_CaptureEntities()
            : base("name=ICT_Bug_CaptureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Document> Documents { get; set; }
        public DbSet<DocumentType> DocumentTypes { get; set; }
        public DbSet<Priority> Priorities { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<System> Systems { get; set; }
        public DbSet<SystemTicket> SystemTickets { get; set; }
        public DbSet<TicketDocument> TicketDocuments { get; set; }
        public DbSet<Ticket> Tickets { get; set; }
        public DbSet<UserTicket> UserTickets { get; set; }
    }
}
