//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugCapture.Domain.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.TicketDocuments = new HashSet<TicketDocument>();
        }
    
        public int DocumentId { get; set; }
        public string Name { get; set; }
        public byte[] Data { get; set; }
        public int DocumentTypeId { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual ICollection<TicketDocument> TicketDocuments { get; set; }
    }
}
